[[questions]]
type = "MultipleChoice"
prompt.prompt = "Which one of the following is NOT true about smart pointers?"
answer.answer = "A smart pointer stores reference to a value and does not provide any memory management."
prompt.distractors = [
	"To prevent unsafe memory access is a primary benefit of smart pointers.",
	"Smart pointers help prevent crashes by avoiding access to unassigned memory cells.",
	"Transferring large data ownership is enhanced using smart pointers"
]
context = """
Smart pointers possess additional metadata and capabilities beyond serving as a reference to a value.
Smart pointers offer memory management feature that extends beyond mere referencing,
it entails memory handling through strict type checking and ownership rules that implement safety measures.
"""

[[questions]]
type = "Tracing"
prompt.program = """
```
#[derive(Drop)]
struct Student {
    name: ByteArray,
    age: u8,
    id: u32
}

fn main() {
    let mut student1 = BoxTrait::new(Student { name: "Peter", age: 12, id: 12345 });
    let student2 = student1;
    student1 = BoxTrait::new(Student { name: "James", age: 18, id: 56789 });
    println!("{}", student2.unbox().name);
}
```
"""
answer.doesCompile = true
answer.stdout = "Peter"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Which of the following statement is TRUE when the following program is run with `scarb cairo-run`?
```
use core::nullable::{NullableTrait, match_nullable, FromNullableResult};

fn main() {
    let mut scoreSheet: Felt252Dict<Nullable<Span<felt252>>> = Default::default();
    
    let exams = array![60, 70, 80, 90];
    scoreSheet.insert(0, NullableTrait::new(exams.span()));
    
    let firstSession = scoreSheet.get(0);

    let record = match match_nullable(firstSession) {
        FromNullableResult::Null => panic!("No value found"),
        FromNullableResult::NotNull(firstSession) => firstSession.unbox(),
    };
    println!("Exams {}", *record.at(4));
}
```
"""
answer.answer = "compiles with a 'Index out of bounds' panic because `zero_default` method is not implemented."
prompt.distractors = [
	"compiles successfully with the output `Exams 90`",
	"compiles with a 'No value found' panic because it implements the `zero_default` method.",
	"Fails to compile with `error: Invalid path.`"
]
context = """
The `Index out of bounds` error occurs due to an attempt to access 
the fifth element of a four-element array, which is not allowed in Cairo.
The error message also indicates that the zero_default method is not called in the code.
"""
